#!/usr/bin/env python3
"""Build GFF3 edge cases from one real public-domain file.

Each output is the source file preserved line for line, with exactly ONE change
to one data row, plus provenance comments appended after the source's own `###`
terminator so the header region stays byte-identical. The `no_version_pragma`
case is the single exception: its one change is the removal of line 1.

Two output directories, because "invalid" and "rejected in practice" are
different things and a consumer picking invalid fixtures must not get a valid
file by mistake:

    data/derived-malformed/    six files that violate the GFF3 specification
    data/derived-edge-cases/   one file that is valid GFF3 and widely refused

These are DERIVED, not found in the wild. They are not evidence about what any
real producer emits, and corpus.yaml labels them that way.

Usage:
    python3 scripts/make_malformed.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_REL = "data/ncbi-refseq/ncbi_refseq_phix174_GCF_000819615.1.gff"
SRC = os.path.join(ROOT, SRC_REL)
BAD = os.path.join(ROOT, "data/derived-malformed")
EDGE = os.path.join(ROOT, "data/derived-edge-cases")

TRAILER = (
    "# derived-from: {src}\n"
    "# single-change: {change}\n"
    "# validity: {validity}\n"
    "# note: generated by scripts/make_malformed.py; see corpus.yaml\n"
)


def data_index(lines, feature_type, occurrence=0):
    """Index of the nth data row of a given feature type."""
    seen = 0
    for i, l in enumerate(lines):
        if l.startswith("#"):
            continue
        cols = l.split("\t")
        if len(cols) >= 3 and cols[2] == feature_type:
            if seen == occurrence:
                return i
            seen += 1
    raise SystemExit(f"no {feature_type} row number {occurrence} in {SRC_REL}")


def set_col(lines, i, col, value):
    out = list(lines)
    cols = out[i].split("\t")
    cols[col] = value
    out[i] = "\t".join(cols)
    return out


def set_attr(lines, i, key, value):
    """Replace an existing attribute, or append it if absent."""
    out = list(lines)
    cols = out[i].split("\t")
    parts = cols[8].split(";")
    for n, p in enumerate(parts):
        if p.startswith(key + "="):
            parts[n] = f"{key}={value}"
            break
    else:
        parts.append(f"{key}={value}")
    cols[8] = ";".join(parts)
    out[i] = "\t".join(cols)
    return out


def build():
    lines = open(SRC).read().splitlines()
    cases = {}

    # --- six that violate the specification -------------------------------

    # Phase in column 8 no longer matches the coordinates. The AgBioData
    # group's headline failure: identical coordinates, different protein.
    i = data_index(lines, "CDS")
    cur = lines[i].split("\t")[7]
    cases["cds_phase_altered.gff3"] = (
        BAD, set_col(lines, i, 7, "1" if cur != "1" else "2"),
        "phase in column 8 of the first CDS changed so it no longer matches the coordinates",
        "invalid: the phase contradicts the frame implied by the coordinates")

    # Parent names an ID defined nowhere. Breaks the graph, not the syntax.
    i = data_index(lines, "CDS")
    cases["dangling_parent.gff3"] = (
        BAD, set_attr(lines, i, "Parent", "gene-DOES-NOT-EXIST"),
        "Parent of the first CDS changed to an ID defined nowhere in the file",
        "invalid: GFF3 requires every Parent to resolve within the file")

    # A raw semicolon inside an attribute value. Must be %3B. Unencoded it
    # silently splits one attribute into two. Note is used rather than product
    # because the first CDS already carries product, and overwriting it would
    # add a second defect.
    i = data_index(lines, "CDS")
    cases["unescaped_semicolon.gff3"] = (
        BAD, set_attr(lines, i, "Note", "coat protein; putative"),
        "a raw semicolon inside a Note value on the first CDS, where GFF3 requires %3B",
        "invalid: the unencoded separator splits one attribute into two")

    # Coordinate inversion. GFF3 requires start <= end for every feature,
    # circular ones included: wraparound is expressed by extending end past
    # the landmark length, never by putting start after end. phiX174 does
    # carry Is_circular=true, which is why this is worth stating explicitly.
    i = data_index(lines, "gene")
    cols = lines[i].split("\t")
    cases["start_after_end.gff3"] = (
        BAD, set_col(set_col(lines, i, 3, cols[4]), i, 4, cols[3]),
        "columns 4 and 5 of the first gene swapped, so start is greater than end",
        "invalid: GFF3 requires start <= end on every feature, circular included")

    # No version pragma. A parser then cannot tell GFF3 from GFF2, and the
    # column 9 grammar differs between them. The only case that changes a
    # header line, and it removes exactly one.
    cases["no_version_pragma.gff3"] = (
        BAD, [l for l in lines if not l.startswith("##gff-version")],
        "the ##gff-version 3 line removed; every other header line preserved",
        "invalid: GFF3 requires the version directive on line 1")

    # One ID on two features, so anything keyed on ID collapses them.
    i = data_index(lines, "gene")
    dup = lines[i].split("\t")
    dup[3], dup[4] = str(int(dup[4]) + 1), str(int(dup[4]) + 50)
    out = list(lines)
    out.insert(i + 1, "\t".join(dup))
    cases["duplicate_id.gff3"] = (
        BAD, out,
        "a second gene row inserted carrying the same ID as the first, at different coordinates",
        "invalid: GFF3 requires ID to be unique within the file")

    # --- one that is valid and widely refused ------------------------------

    # Two parents on one feature. LEGAL GFF3. The AgBioData recommendations
    # ask that parsers keep supporting it, and many refuse it. Both parents
    # are defined in the source, so this file is valid and nothing else about
    # it is wrong: gene-phiX174p06 contains rna-phiX174p06, and the CDS is a
    # child of the transcript.
    i = data_index(lines, "CDS", occurrence=2)
    cur_parent = dict(p.split("=", 1) for p in lines[i].split("\t")[8].split(";"))["Parent"]
    cases["multiple_parents.gff3"] = (
        EDGE, set_attr(lines, i, "Parent", f"{cur_parent},gene-phiX174p06"),
        f"a second Parent, gene-phiX174p06, added beside {cur_parent}; both are defined in this file",
        "VALID GFF3: multiple parents are permitted, and many tools refuse them anyway")

    for d in (BAD, EDGE):
        os.makedirs(d, exist_ok=True)
    for name, (dest, body, change, validity) in sorted(cases.items()):
        text = "\n".join(body) + "\n" + TRAILER.format(
            src=SRC_REL, change=change, validity=validity)
        p = os.path.join(dest, name)
        open(p, "w").write(text)
        print(f"{os.path.getsize(p):>6}  {os.path.relpath(p, ROOT)}")
    return cases


if __name__ == "__main__":
    build()
