#!/usr/bin/env python3
"""Build GFF3 edge cases from one real public-domain file.

Each output is the source file preserved line for line, with exactly ONE change
to one data row, plus provenance comments appended after the source's own `###`
terminator so the header region stays byte-identical. The `no_version_pragma`
case is the single exception: its one change is the removal of line 1.

Two output directories, because "invalid" and "rejected in practice" are
different things and a consumer picking invalid fixtures must not get a valid
file by mistake:

    data/derived-malformed/    six files that violate the GFF3 specification
    data/derived-edge-cases/   three files that are valid GFF3 and still wrong in practice

These are DERIVED, not found in the wild. They are not evidence about what any
real producer emits, and corpus.yaml labels them that way.

Usage:
    python3 scripts/make_malformed.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_REL = "data/ncbi-refseq/ncbi_refseq_phix174_GCF_000819615.1.gff"
SRC = os.path.join(ROOT, SRC_REL)
BAD = os.path.join(ROOT, "data/derived-malformed")
EDGE = os.path.join(ROOT, "data/derived-edge-cases")

TRAILER = (
    "# derived-from: {src}\n"
    "# single-change: {change}\n"
    "# validity: {validity}\n"
    "# note: generated by scripts/make_malformed.py; see corpus.yaml\n"
)


def data_index(lines, feature_type, occurrence=0):
    """Index of the nth data row of a given feature type."""
    seen = 0
    for i, l in enumerate(lines):
        if l.startswith("#"):
            continue
        cols = l.split("\t")
        if len(cols) >= 3 and cols[2] == feature_type:
            if seen == occurrence:
                return i
            seen += 1
    raise SystemExit(f"no {feature_type} row number {occurrence} in {SRC_REL}")


def set_col(lines, i, col, value):
    out = list(lines)
    cols = out[i].split("\t")
    cols[col] = value
    out[i] = "\t".join(cols)
    return out


def set_attr(lines, i, key, value):
    """Replace an existing attribute, or append it if absent."""
    out = list(lines)
    cols = out[i].split("\t")
    parts = cols[8].split(";")
    for n, p in enumerate(parts):
        if p.startswith(key + "="):
            parts[n] = f"{key}={value}"
            break
    else:
        parts.append(f"{key}={value}")
    cols[8] = ";".join(parts)
    out[i] = "\t".join(cols)
    return out


def build():
    lines = open(SRC).read().splitlines()
    cases = {}

    # --- six that violate the specification -------------------------------

    # Phase outside the permitted set. GFF3 allows only 0, 1 and 2 on a CDS,
    # so 3 is a specification violation rather than a judgement call.
    i = data_index(lines, "CDS")
    cases["cds_phase_illegal.gff3"] = (
        BAD, set_col(lines, i, 7, "3"),
        "phase in column 8 of the first CDS set to 3, outside the permitted 0, 1 and 2",
        "invalid: GFF3 permits only 0, 1 or 2 in the phase column")

    # Parent names an ID defined nowhere. Breaks the graph, not the syntax.
    i = data_index(lines, "CDS")
    cases["dangling_parent.gff3"] = (
        BAD, set_attr(lines, i, "Parent", "gene-DOES-NOT-EXIST"),
        "Parent of the first CDS changed to an ID defined nowhere in the file",
        "invalid: GFF3 requires every Parent to resolve within the file")

    # A raw semicolon inside an attribute value, where GFF3 requires %3B.
    # What the parser then sees is " putative", a segment with no tag=value
    # form at all, so a conforming parser must reject it. Note rather than
    # product, because the first CDS already carries product and overwriting
    # it would add a second defect.
    i = data_index(lines, "CDS")
    cases["unescaped_semicolon.gff3"] = (
        BAD, set_attr(lines, i, "Note", "coat protein; putative"),
        "a raw semicolon inside a Note value on the first CDS, where GFF3 requires %3B",
        "invalid: the text after the separator is a bare segment with no tag=value form, "
        "which a conforming parser must reject")

    # Coordinate inversion. GFF3 requires start <= end for every feature,
    # circular ones included: wraparound is expressed by extending end past
    # the landmark length, never by putting start after end. phiX174 does
    # carry Is_circular=true, which is why this is worth stating explicitly.
    i = data_index(lines, "gene")
    cols = lines[i].split("\t")
    cases["start_after_end.gff3"] = (
        BAD, set_col(set_col(lines, i, 3, cols[4]), i, 4, cols[3]),
        "columns 4 and 5 of the first gene swapped, so start is greater than end",
        "invalid: GFF3 requires start <= end on every feature, circular included")

    # No version pragma. A parser then cannot tell GFF3 from GFF2, and the
    # column 9 grammar differs between them. The only case that changes a
    # header line, and it removes exactly one.
    cases["no_version_pragma.gff3"] = (
        BAD, [l for l in lines if not l.startswith("##gff-version")],
        "the ##gff-version 3 line removed; every other header line preserved",
        "invalid: GFF3 requires the version directive on line 1")

    # One ID on two features of DIFFERENT type. Repeating an ID is not by
    # itself an error: GFF3 permits a discontinuous feature to span several
    # lines under a shared ID, provided every line describes the same feature.
    # Two different types cannot be the same feature, so this collision is a
    # genuine violation where simply duplicating a row would not have been.
    gi = data_index(lines, "gene")
    gene_id = dict(p.split("=", 1) for p in lines[gi].split("\t")[8].split(";"))["ID"]
    ai = data_index(lines, "sequence_alteration")
    cases["duplicate_id.gff3"] = (
        BAD, set_attr(lines, ai, "ID", gene_id),
        f"the first sequence_alteration given the first gene's ID, {gene_id}, so one ID "
        f"names two features of different type",
        "invalid: a repeated ID is only legal across lines describing one feature, and "
        "these differ in type")

    # --- three that are valid GFF3 and still problems ----------------------

    # The silent version of the semicolon problem, and the dangerous one. Here
    # the text after the unescaped separator does have tag=value form, and the
    # tag is lowercase, which the specification reserves for free use by
    # applications. So the file is VALID, the intended Note is truncated, and a
    # note attribute nobody wrote now exists. Nothing reports anything.
    i = data_index(lines, "CDS")
    cases["unescaped_semicolon_silent.gff3"] = (
        EDGE, set_attr(lines, i, "Note", "coat protein;note=putative"),
        "an unescaped semicolon in a Note value whose tail is itself a valid lowercase "
        "tag=value pair",
        "VALID GFF3: the Note is silently truncated and a second attribute appears that "
        "nobody wrote; no validator reports anything because nothing is malformed")


    # Phase changed to another permitted value. This is the failure the
    # AgBioData group leads with, and it is NOT a specification violation:
    # 0, 1 and 2 are all legal, so no syntax-only validator can catch it.
    # Translating the CDS against the reference protein does catch it.
    # Identical coordinates with a different phase give a different protein.
    i = data_index(lines, "CDS")
    cur = lines[i].split("\t")[7]
    cases["cds_phase_biologically_wrong.gff3"] = (
        EDGE, set_col(lines, i, 7, "1" if cur != "1" else "2"),
        f"phase in column 8 of the first CDS changed from {cur} to another permitted value",
        "VALID GFF3: 0, 1 and 2 are all legal, so no syntax-only validator catches "
        "this; translating against the reference protein does. The annotation is "
        "biologically wrong rather than malformed")


    # Two parents on one feature. LEGAL GFF3. The AgBioData recommendations
    # ask that parsers keep supporting it, and many refuse it. Both parents
    # are defined in the source, so this file is valid and nothing else about
    # it is wrong: gene-phiX174p06 contains rna-phiX174p06, and the CDS is a
    # child of the transcript.
    i = data_index(lines, "CDS", occurrence=2)
    cur_parent = dict(p.split("=", 1) for p in lines[i].split("\t")[8].split(";"))["Parent"]
    cases["multiple_parents.gff3"] = (
        EDGE, set_attr(lines, i, "Parent", f"{cur_parent},gene-phiX174p06"),
        f"a second Parent, gene-phiX174p06, added beside {cur_parent}; both are defined in this file",
        "VALID GFF3: multiple parents are permitted, and many tools refuse them anyway")

    for d in (BAD, EDGE):
        os.makedirs(d, exist_ok=True)
    for name, (dest, body, change, validity) in sorted(cases.items()):
        text = "\n".join(body) + "\n" + TRAILER.format(
            src=SRC_REL, change=change, validity=validity)
        p = os.path.join(dest, name)
        open(p, "w").write(text)
        print(f"{os.path.getsize(p):>6}  {os.path.relpath(p, ROOT)}")
    return cases


if __name__ == "__main__":
    build()
